# This file was generated by GoReleaser. DO NOT EDIT.
cask "timer" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "5cbb0c738db57461dba2340fd4586a18f703e5b577b2b7f95e77ea439a729ae7"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6437a7ca5a5ee293acf0c74b5b54bd51f4aea4310bc66d7e585adca77e4ccf85"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ff24d7122abeb34f4491f94da7025daae3a9530f363eebe3dd1cc02426a5776"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9948ad7ebe06464b4a7d44136f10e67c99c38e5303836ec7ecb157da22d57532"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "timer"
  desc "Local-first time tracker with CLI, TUI and MCP"
  homepage "https://github.com/AngheloAlva/timer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "timer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/timer"]
    end
  end

  # No zap stanza required

end
