# This file was generated by GoReleaser. DO NOT EDIT.
cask "timer" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "7c5ea825bbd914959319c0b83555617b71dc9cbee480d2fa46a98640b8d7bd20"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c627debb0272291569b9a189f293a73e003daf8e0d934fff7b9a290327658ccf"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "be112f0537e565baa841df20fe0dc8372b8d56286f98aabe65697174e131e470"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2570c6ff66905625c78a0c1a9176be252d6bf93004137152b754b51428ac418a"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "timer"
  desc "Local-first time tracker with CLI, TUI and MCP"
  homepage "https://github.com/AngheloAlva/timer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "timer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/timer"]
    end
  end

  # No zap stanza required

end
