# This file was generated by GoReleaser. DO NOT EDIT.
cask "timer" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "1273a968b76739724d6545c898ce082620f778ef7f71bad72185fbafda281d3b"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15634b82ee073dee5db2e4d17ee6b39a40e32ecd60d277669e6d3a0d75a26b34"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "12ed1062b3d21433a28ba5fff1eac4724c79fcbb3bdb44e10b79c4eaf490fb77"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "243645065116d1de784ba95a4c3722719c6704be868f0257342d89351e74ce88"
      url "https://github.com/AngheloAlva/timer/releases/download/v#{version}/timer_#{version}_linux_arm64.tar.gz"
    end
  end

  name "timer"
  desc "Local-first time tracker with CLI, TUI and MCP"
  homepage "https://github.com/AngheloAlva/timer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "timer"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/timer"]
    end
  end

  # No zap stanza required

end
